### ISSUE TITLE
Internal Compiler Error: Could not find type declaration for 'Map_Header'

### ISSUE THREAD

**Issue by hrumy** [oskarnp/odin-tracy#4]
Upon running the last command from the installation guide ( `odin run . -define:TRACY_ENABLE=true` ) , i get the following error. 
> Internal Compiler Error: Could not find type declaration for 'Map_Header'

**Comment by oskarnp** [comment]
@hrumy Did you by chance update to latest Odin but forgot to rebuild odin exe? It looks like you are using an old odin exe but a new core library or other way around.

**Comment by hrumy** [comment]
Thank you, this resolved the issue. Sorry for wasting your time.
